### ISSUE TITLE
_getUsingCursor function fetch signature

### ISSUE THREAD

**Issue by tcr** [AvianFlu/ntwitter#8]
Line 1144, the function signature for fetch should be:

```
function fetch(err, data) {
```

Which adds the "err" parameter.

I can make a pull request if you'd like.

**Comment by AvianFlu** [comment]
I must have missed that one when I fixed most of them after forking the project (this library originally returned err OR result to every callback) - thanks for pointing it out.  If you've got the time, I'd definitely accept a pull request for this - otherwise I'll be able to look into it a little later.

Thanks again for the feedback!
