### ISSUE TITLE
Question on API limits for users/lookup

### ISSUE THREAD

**Issue by AvnerCohen** [AvianFlu/ntwitter#80]
Question related to the API limits, It might something I'm just missing, not sure though:

If I do this:

``` javascript
     twit.showUser(ids, function(error, response) {
       console.log(response)
     }
```

Where {ids} is an Array, with length < 100, all is well.

When I do the same and IDs is > 100, it fails.

This is based on:
https://dev.twitter.com/docs/api/1.1/get/users/lookup

And specifically:

> for up to 100 users per request

Is this somehow managed in ntwitter or do I need to manage this outside? if so, any recommendation on how to manage that?

**Comment by NachoSoto** [comment]
This is something I've implemented in my own fork: https://github.com/NachoSoto/ntwitter/commit/d2a8577c526b981262a4b07f7b25f7176f364f49
I automatically throttle the requests so that I can fetch more data like in the example you provided.
I opened a pull request a while ago (#77) but it doesn't seem like it'll be merged... so feel free to try out my implementation :-)

**Comment by AvnerCohen** [comment]
Thanks. I hacked this bit with a really ugly code, I'll take a look at your solution.
